### ISSUE TITLE
nupkg Support

### ISSUE THREAD

**Issue by gpltaylor** [OctopusDeploy/gulp-octo#5]
when packing using nupkg I get the following error despite the document stating support for this format:

`
[11:19:26] Error: Currently unable to support .nupkg file. Please use .tar.gz or .zip
    at formatError (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\index.js:264:8)
    at D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\index.js:275:23
    at finish (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\lib\runTask.js:36:10)
    at Gulp.Orchestrator._runTask (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Desktop\Development Area\ProtoTypes\OctopackApp\octofxjs\node_modules\orchestrator\index.js:214:10)
`

this is using Gulp
`gulp.task('publish', ['bump', 'build'], function () {
  return gulp.src(['**/*', '!bin{,/**}', '!src{,/**}', '!gulpfile.js'])
      .pipe(octo.pack('nupkg'))
      .pipe(octo.push({apiKey: 'API-##removed##', host: '##removed##'}));
});`

This is using the demo app: octofxjs

**Comment by zentron** [comment]
@gpltaylor: due to constant reports of issues with nuget files constructed through nodejs, https://github.com/OctopusDeploy/octopackjs was changed to no longer support packaging with the NuGet format.
Packaging as a tar or zip (which is essentially what a `.nupkg` file is with some extra metadata) should have no difference to your Octopus Deploy server once its been pushed. Apologies for any inconvenience

**Comment by gpltaylor** [comment]
No probs, the issue was that I was still running in Octopus Server 2. This did not support zip and only supported NuGet, making this lib a little useless for me :)

I have updated our servers to the latest version, so we are not using pure Zip from now on.
